import type { ExternalCatalogItem } from "@/types/project";

export const skillsSnapshot: ExternalCatalogItem[] = [
  {
    id: "skills-sh:vercel-labs/skills/find-skills",
    kind: "skills",
    source: "skills-sh",
    sourceLabel: "skills.sh",
    title: "find-skills",
    summary: "관련 스킬을 빠르게 찾을 수 있도록 도와주는 탐색용 인기 스킬입니다.",
    owner: "vercel-labs",
    repo: "vercel-labs/skills",
    slug: "find-skills",
    url: "https://skills.sh/vercel-labs/skills/find-skills",
    repoUrl: "https://github.com/vercel-labs/skills",
    installCommand:
      "npx skills add https://github.com/vercel-labs/skills --skill find-skills",
    tags: ["discover", "search", "skills", "catalog"],
    categories: ["탐색"],
    popularityValue: 687200,
    popularityLabel: "687.2K 설치",
  },
  {
    id: "skills-sh:anthropics/skills/frontend-design",
    kind: "skills",
    source: "skills-sh",
    sourceLabel: "skills.sh",
    title: "frontend-design",
    summary: "프론트엔드 화면 설계에 도움을 주는 인기 스킬입니다.",
    owner: "anthropics",
    repo: "anthropics/skills",
    slug: "frontend-design",
    url: "https://skills.sh/anthropics/skills/frontend-design",
    repoUrl: "https://github.com/anthropics/skills",
    installCommand:
      "npx skills add https://github.com/anthropics/skills --skill frontend-design",
    tags: ["frontend", "design", "ui", "ux"],
    categories: ["디자인"],
    popularityValue: 192600,
    popularityLabel: "192.6K 설치",
  },
  {
    id: "skills-sh:vercel-labs/agent-skills/web-design-guidelines",
    kind: "skills",
    source: "skills-sh",
    sourceLabel: "skills.sh",
    title: "web-design-guidelines",
    summary: "웹 디자인 기준을 빠르게 잡는 데 도움을 주는 인기 스킬입니다.",
    owner: "vercel-labs",
    repo: "vercel-labs/agent-skills",
    slug: "web-design-guidelines",
    url: "https://skills.sh/vercel-labs/agent-skills/web-design-guidelines",
    repoUrl: "https://github.com/vercel-labs/agent-skills",
    installCommand:
      "npx skills add https://github.com/vercel-labs/agent-skills --skill web-design-guidelines",
    tags: ["web", "design", "frontend", "guidelines"],
    categories: ["디자인"],
    popularityValue: 193400,
    popularityLabel: "193.4K 설치",
  },
  {
    id: "claude-marketplaces:skills:anthropics/skills/frontend-design",
    kind: "skills",
    source: "claude-marketplaces",
    sourceLabel: "Claude Marketplaces",
    title: "frontend-design",
    summary: "frontend-design 관련 커뮤니티 디렉터리 항목입니다.",
    owner: "anthropics",
    repo: "anthropics/skills",
    slug: "frontend-design",
    url: "https://claudemarketplaces.com/skills/anthropics/skills/frontend-design",
    repoUrl: "https://github.com/anthropics/skills",
    installCommand:
      "npx skills add https://github.com/anthropics/skills --skill frontend-design",
    tags: ["frontend", "design", "claude", "skills"],
    categories: ["커뮤니티"],
    popularityValue: 186400,
    popularityLabel: "186.4K 설치",
  },
  {
    id: "claude-marketplaces:skills:vercel-labs/agent-skills/vercel-react-best-practices",
    kind: "skills",
    source: "claude-marketplaces",
    sourceLabel: "Claude Marketplaces",
    title: "vercel-react-best-practices",
    summary: "React 구현 관점에서 자주 참고되는 커뮤니티 스킬 항목입니다.",
    owner: "vercel-labs",
    repo: "vercel-labs/agent-skills",
    slug: "vercel-react-best-practices",
    url: "https://claudemarketplaces.com/skills/vercel-labs/agent-skills/vercel-react-best-practices",
    repoUrl: "https://github.com/vercel-labs/agent-skills",
    installCommand:
      "npx skills add https://github.com/vercel-labs/agent-skills --skill vercel-react-best-practices",
    tags: ["react", "vercel", "frontend", "best-practices"],
    categories: ["커뮤니티"],
    popularityValue: 235800,
    popularityLabel: "235.8K 설치",
  },
];

export const marketplacesSnapshot: ExternalCatalogItem[] = [
  {
    id: "claude-marketplaces:marketplace:anthropics/claude-code",
    kind: "marketplaces",
    source: "claude-marketplaces",
    sourceLabel: "Claude Marketplaces",
    title: "anthropics/claude-code",
    summary: "Claude Code 관련 플러그인 묶음을 모아둔 커뮤니티 마켓 항목입니다.",
    owner: "anthropics",
    repo: "anthropics/claude-code",
    slug: "anthropics-claude-code",
    url: "https://claudemarketplaces.com/plugins/anthropics-claude-code",
    repoUrl: "https://github.com/anthropics/claude-code",
    tags: ["development", "productivity", "security", "sdk"],
    categories: ["development", "productivity", "learning", "security"],
    popularityValue: 65114,
    popularityLabel: "8개 플러그인 / 65.1K 스타",
  },
  {
    id: "claude-marketplaces:marketplace:payloadcms/payload",
    kind: "marketplaces",
    source: "claude-marketplaces",
    sourceLabel: "Claude Marketplaces",
    title: "payloadcms/payload",
    summary: "Payload 관련 플러그인 묶음을 볼 수 있는 커뮤니티 마켓 항목입니다.",
    owner: "payloadcms",
    repo: "payloadcms/payload",
    slug: "payloadcms-payload",
    url: "https://claudemarketplaces.com/plugins/payloadcms-payload",
    repoUrl: "https://github.com/payloadcms/payload",
    tags: ["payload", "development", "plugin"],
    categories: ["커뮤니티"],
    popularityValue: 40754,
    popularityLabel: "1개 플러그인 / 40.8K 스타",
  },
  {
    id: "claude-marketplaces:marketplace:eyaltoledano/claude-task-master",
    kind: "marketplaces",
    source: "claude-marketplaces",
    sourceLabel: "Claude Marketplaces",
    title: "eyaltoledano/claude-task-master",
    summary: "작업 관리 흐름에 특화된 커뮤니티 마켓 항목입니다.",
    owner: "eyaltoledano",
    repo: "eyaltoledano/claude-task-master",
    slug: "eyaltoledano-claude-task-master",
    url: "https://claudemarketplaces.com/plugins/eyaltoledano-claude-task-master",
    repoUrl: "https://github.com/eyaltoledano/claude-task-master",
    tags: ["automation", "workflow", "task-management"],
    categories: ["productivity"],
    popularityValue: 25342,
    popularityLabel: "1개 플러그인 / 25.3K 스타",
  },
];
